name: reviewdog
on: [pull_request]
env:
  ESLINT_USE_FLAT_CONFIG: true
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: yarn workspace google-nest-notifier install
      - run: yarn workspace google-nest-notifier build
      - run: yarn install
      - name: eslint
        uses: reviewdog/action-eslint@v1.32.0
        with:
          level: warning
          reporter: github-pr-review
          filter_mode: nofilter
          fail_on_error: false # because level is warning
          eslint_flags: '--config eslint.config.mjs'
